
export PATH="$HOME/bin:$PATH";
export BASH_SILENCE_DEPRECATION_WARNING=1

source ~/.aliases
source ~/.bash_prompt

# ascii art generator: https://patorjk.com/software/taag
# cd ~/art
# cat [name].ascii.txt | gzip | base64 > [name].art
# ln [name].art selected.art
# uncompress and display ascii art!
#base64 -d<<<$(cat ~/art/selected.art) | gunzip

[[ -r "/usr/local/etc/profile.d/bash_completion.sh" ]] && . "/usr/local/etc/profile.d/bash_completion.sh"
