#!/usr/bin/env bash

# GIT FUNCTIONS

git_repo() {
    git remote -v | grep 'fetch' | sed -e 's/^.*\/\([[:alnum:]].*\)\.git.*$/\1/g'
}

git_branch() {
    git branch 2>/dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
}

export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad

# TERMINAL PROMPT

PS1="\r\n"
PS1+="\[\`if [[ \$? = "0" ]]; then echo '\e[32m\h\e[0m'; else echo '\e[31m\h\e[0m' ; fi\`:\$PWD\n\$ "
PS1+="\[\e[0;93m\]\u\[\e[m\]"    # username
#PS1+="|\[\e[0;95m\]\W\[\e[m\]"    # current directory
PS1+="\[\e[0;92m\]\$(git_branch)\[\e[m\]"   # current branch
PS1+=" "      # space
PS1+=">> "    # end prompt

export PS1;
